// form_react/src/components/info/card/infoCard.tsx
import * as React from 'React';
import './infoCard.scss';

export interface InfoCardType {
    img: string;
    name: string;
    text: string;
}

interface InfoCardProps {
    infoList: InfoCardType[];
}

export class InfoCard extends React.Component<InfoCardProps> {
    render() {
        return (
            <section className="promotion-section">
                <div className="container">
                    <ul className="promo-list">
                        {this.props.infoList.map(
                            (item: InfoCardType, idx: number) => {
                                return (
                                    <li key={idx}>
                                        <a href="#">
                                            <img src={item.img} alt="" />
                                            <h3>{item.name}</h3>
                                            <p>{item.text}</p>
                                        </a>
                                    </li>
                                );
                            }
                        )}
                    </ul>
                </div>
            </section>
        );
    }
}

// form_ang/src/app/components/info-section/info-card/info-card.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-info-card',
  templateUrl: './info-card.component.html',
  styleUrls: ['./info-card.component.scss']
})
export class InfoCardComponent implements OnInit {
  @Input() infoList: InfoCard[];
  constructor() {}

  ngOnInit() {}
}
export interface InfoCard {
  img: string;
  name: string;
  text: string;
}

<section class="promotion-section">
  <div class="container">
    <ul class="promo-list">
      <li *ngFor="let item of infoList">
        <a href="#">
          <img [src]="item.img" alt="">
          <h3>{{item.name}}</h3>
          <p>{{item.text}}</p>
        </a>
      </li>
    </ul>
  </div>
</section>
