// form_ang/src/layout/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';
import { Model } from '../../model/model';

@Component({
  selector: 'app-layout',
  templateUrl: './layout.component.html',
  styleUrls: ['./layout.component.scss']
})
export class LayoutComponent implements OnInit {
  constructor(private menuModel: Model) {}

  ngOnInit() {}

  scrollTo(id: string): void {
    const element = document.querySelector('#' + id);
    if (element) {
      setTimeout(() => {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 0);
    }
  }
}

<header class="form-ang-header">
  <app-header [menuLists]="menuModel.menuLists" (scrollEvent)="scrollTo($event)"></app-header>
</header>
<section class="form-ang-contents">
  <app-slider-section></app-slider-section>
  <app-info-section id="weare"></app-info-section>
  <app-work-section></app-work-section>
  <app-blog-section></app-blog-section>
  <app-contact-section></app-contact-section>
</section>
<footer class="form-ang-footer">
  <app-footer></app-footer>
</footer>

// form_react/src/layout/layout/layout.tsx
import * as React from 'react';
import { Footer } from '../footer/footer';
import { MenuList, Header } from '../header/header';
import { ImgSlider } from '../../components/Imgslider/imgSlider';
import { Info } from '../../components/info/info';
import { Work } from '../../components/work/work';
import { Blog } from '../../components/blog/blog';
import './layout.scss';
import { Contact } from '../../components/contact/contact';

export class Layout extends React.Component {
    menuLists: MenuList[] = [
        {
            name: 'HOME',
            section: 'home_section'
        },
        {
            name: 'WE ARE',
            section: 'weare_section'
        },
        {
            name: 'WORK',
            section: 'work_section'
        },
        {
            name: 'BLOG',
            section: 'blog_section'
        },
        {
            name: 'CONTACT US',
            section: 'contact_section'
        }
    ];
    scrollTo(id: string, callBack: Function): void {
        const element = document.querySelector('#' + id);
        if (element) {
            setTimeout(() => {
                element.scrollIntoView({ behavior: 'smooth', block: 'start' });
                callBack();
            }, 0);
        }
    }
    render() {
        return (
            <div>
                <Header menuLists={this.menuLists} scrollTo={this.scrollTo} />
                <section>
                    <ImgSlider />
                    <Info />
                    <Work />
                    <Blog />
                    <Contact />
                </section>
                <Footer />
            </div>
        );
    }
}
